name: samigo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.0
  http: ^1.2.2
  speech_to_text: ^7.0.0
  google_sign_in: ^6.2.2
  googleapis_auth: ^1.6.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
